// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Make Caddyfile
---
*/
package endpoints

import (
	"context"

	"github.com/swaggest/usecase"

	"github.com/365admin/koksmat-door/execution"
)

func MagicMakePost() usecase.Interactor {
	type Request struct {
		Test string `query:"test" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "koksmat-door", "00-magic", "30-buildcaddyfile.ps1", "", "-test", input.Test)
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Make Caddyfile")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Magic Buttons")
	return u
}
